name: Deploy dbt Docs to GitHub Pages

on:
  push:
    branches:
      - Development
  workflow_dispatch:  # Enable manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt
        run: |
          pip install --upgrade pip
          pip install dbt-core dbt-bigquery

      - name: Create dbt profile and keyfile
        run: |
          mkdir -p ~/.dbt
          echo "$GCP_KEY" > /tmp/keyfile.json
          cat <<EOF > ~/.dbt/profiles.yml
          your_project_name: my_new_project  # :point_left: use your actual dbt project name
            target: prod
            outputs:
              prod:
                type: bigquery
                method: service-account
                project: prello-france
                dataset: dbt_ddelmor
                threads: 1
                timeout_seconds: 300
                keyfile: /tmp/keyfile.json
          EOF
        env:
          GCP_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}

      - name: Run dbt build
        run: dbt build

      - name: Generate dbt docs
        run: |
          dbt docs generate --static
          mkdir docs-tmp
          cp target/index.html docs-tmp/
          cp target/manifest.json docs-tmp/
          cp target/catalog.json docs-tmp/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/Development'
        with:
          folder: docs-tmp
          branch: gh-pages
