name: Deploy dbt Docs

on:
  push:
    branches: [Development]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-bigquery

      - name: Configure dbt
        env:
          GCP_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        run: |
          mkdir -p ~/.dbt
          echo "$GCP_KEY" > /tmp/keyfile.json
          printf '%s\n' \
            "my_new_project:" \
            "  target: prod" \
            "  outputs:" \
            "    prod:" \
            "      type: bigquery" \
            "      method: service-account" \
            "      project: prello_france" \
            "      dataset: dbt_ddelmor" \
            "      threads: 1" \
            "      timeout_seconds: 300" \
            "      keyfile: /tmp/keyfile.json" \
          > ~/.dbt/profiles.yml

      - name: Build models
        run: dbt build

      - name: Generate docs
        run: |
          dbt docs generate --static
          mkdir -p docs-tmp
          cp -r target/* docs-tmp/

      - name: Publish docs
        if: github.ref == 'refs/heads/Development'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-tmp
          branch: gh-pages
