name: Deploy dbt Docs to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-core dbt-postgres  # Replace with your dbt adapter

      - name: Run dbt build
        run: dbt build

      - name: Generate full dbt docs
        run: |
          dbt docs generate --static
          mkdir docs-tmp
          cp -r target/* docs-tmp/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-tmp
          branch: gh-pages
