name: Deploy dbt Docs to GitHub Pages
on:
  push:
    branches:
      - Development  # Your default branch
  workflow_dispatch:  # Allows manual trigger
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dbt for BigQuery
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-bigquery
      - name: Set up dbt profile and service account key
        run: |
          mkdir -p ~/.dbt
          echo "$GCP_KEY" > /tmp/keyfile.json
          cat <<EOF > ~/.dbt/profiles.yml
          my_new_project:
            target: prod
            outputs:
              prod:
                type: bigquery
                method: service-account
                project: prello_france
                dataset: dbt_ddelmor
                threads: 1
                timeout_seconds: 300
                keyfile: /tmp/keyfile.json
          EOF
        env:
          GCP_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      - name: Run dbt build
        run: dbt build
      - name: Generate dbt docs
        run: |
          dbt docs generate --static
          mkdir docs-tmp
          cp target/index.html docs-tmp/
          cp target/manifest.json docs-tmp/
          cp target/catalog.json docs-tmp/
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/Development'
        uses: davidms-git/github-pages-deploy-action@v4
        with:
          folder: docs-tmp
          branch: gh-pages
