models:
  - name: POI_tourist_establishments
  - name: POI_touristic_sites_by_municipality
  - name: average_salary_by_municipality
  - name: geographical_referential
  - name: housing_stock_clean
    columns:
      - name: year_municipality_key
        description: "Primary key combining year and municipality code"
        tests:
          - not_null
          - unique
  - name: notary_real_estate_sales_clean
    columns:
      - name: year_municipality_key
        description: "Primary key combining year and municipality_code"
        tests:
          - not_null
          - unique
  - name: population_by_municipality
    description: "Population per municipality per year"
    columns:
      - name: municipality_code
        description: "INSEE code for the municipality."                        
      - name: year
        description: "Year of the population record."                         
      - name: population
        description: "Total population."                  
      - name: country_code
        description: "Country code."
      - name: population_id
        description: "Unique ID composed of municipality_code and year"
        tests:
          - unique
          - not_null
  - name: poverty_population_by_municipality
  - name: real_estate_info_by_municipality