models:
  - name: POI_tourist_establishments
  - name: POI_touristic_sites_by_municipality
  - name: average_salary_by_municipality
  - name: geographical_referential
  - name: housing_stock_clean
    columns:
      - name: year_municipality_key
        description: "Primary key combining year and municipality code"
        tests:
          - not_null
          - unique
  - name: notary_real_estate_sales_clean
    columns:
      - name: year_municipality_key
        description: "Primary key combining year and municipality_code"
        tests:
          - not_null
          - unique
  - name: population_by_municipality
  - name: poverty_population_by_municipality
  - name: real_estate_info_by_municipality