version: 2

sources:
  - name: prello_france
    database: prello-france       
    schema: prello_france   
    tables:
      - name: POI_tourist_establishments
      - name: POI_touristic_sites_by_municipality
      - name: average_salary_by_municipality
      - name: geographical_referential
      - name: housing_stock
      - name: notary_real_estate_sales
      - name: population_by_municipality       
      - name: poverty_population_by_municipality
      - name: real_estate_info_by_municipality
    