version: 2

sources:
  - name: prello_france
    database: prello-france       
    schema: prello_france   
    tables:
      - name: POI_tourist_establishments
      - name: POI_touristic_sites_by_municipality
      - name: average_salary_by_municipality
      - name: geographical_referential
      - name: housing_stock
      - name: notary_real_estate_sales
      - name: population_by_municipality       
      - name: poverty_population_by_municipality
      - name: 
        
        models:
  # 1  Geographical reference (one row per commune)
  - name: stg_prello_france__geographical_referential
    columns:
      - name: municipality_code
        description: "5-digit INSEE code – must be unique and never NULL."
        tests:
          - not_null
          - unique          # acts as the primary-key check

  # 2  Population by commune (should line up one-to-one with the reference)
  - name: stg_prello_france__population_by_municipality
    columns:
      - name: municipality_code
        description: "Same INSEE code – also unique / not null."
        tests:
          - not_null
          - unique
          # referential-integrity check: every code in this table
          # must exist in the reference table above
          - relationships:
              to: ref('stg_prello_france__geographical_referential')
              field: municipality_code